services:
  - type: web
    name: trading-tools-app
    runtime: docker
    repo: https://github.com/Yusuprozimemet/trading-tools.git
    branch: main
    dockerfilePath: ./Dockerfile
    region: oregon # or singapore, ohio, frankfurt
    plan: free # or starter, standard, pro
    healthCheckPath: /
